import Head from 'next/head'
import Image from 'next/image'
import Map from '../components/Map'
import styles from '../styles/Home.module.css'

export default function Home({spaceXPads}) {

  return (
    <div >
      <Head>
        <title>Space x api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<Map spaceXPads={spaceXPads}/>
    </div>
  )
}



export async function getServerSideProps(){


  const spaceXPads=await fetch("https://api.spacexdata.com/v3/landpads")
  .then(res=>res.json())

  return{
    props:{
      spaceXPads
    }
  }


}
